// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20240429140927_now")]
    partial class now
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EL.Faturalar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("FaturaAciklamasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FaturaTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HesapId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("KullanicilarId")
                        .HasColumnType("int");

                    b.Property<string>("OdemeDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HesapId");

                    b.HasIndex("KullanicilarId");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("EL.Hesaplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bakiye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HesapNumarasi")
                        .HasColumnType("int");

                    b.Property<int>("HesapTuru")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("HesapBilgileri");
                });

            modelBuilder.Entity("EL.IslemGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HesapNumarasi")
                        .HasColumnType("int");

                    b.Property<int>("HesapNumarasi2")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IslemTutari")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HesapNumarasi2");

                    b.ToTable("IslemGecmisi");
                });

            modelBuilder.Entity("EL.Kullanicilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("EL.Faturalar", b =>
                {
                    b.HasOne("EL.Hesaplar", "Hesaplar")
                        .WithMany("Faturalar")
                        .HasForeignKey("HesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EL.Kullanicilar", null)
                        .WithMany("Faturalar")
                        .HasForeignKey("KullanicilarId");

                    b.Navigation("Hesaplar");
                });

            modelBuilder.Entity("EL.Hesaplar", b =>
                {
                    b.HasOne("EL.Kullanicilar", "Kullanicilar")
                        .WithMany("Hesaplar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("EL.IslemGecmisi", b =>
                {
                    b.HasOne("EL.Hesaplar", "Hesaplar")
                        .WithMany("IslemGecmis")
                        .HasForeignKey("HesapNumarasi2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hesaplar");
                });

            modelBuilder.Entity("EL.Hesaplar", b =>
                {
                    b.Navigation("Faturalar");

                    b.Navigation("IslemGecmis");
                });

            modelBuilder.Entity("EL.Kullanicilar", b =>
                {
                    b.Navigation("Faturalar");

                    b.Navigation("Hesaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
